version: '2'

networks:
  app-tier:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking_be_container
    # Production environment
    command: yarn start:prod
    env_file:
      - src/.env.stage.prod
    # Development environment
    # command: yarn start:dev
    # env_file:
    #   - src/.env.stage.dev
    ports:
      - '4000:4000'
    depends_on:
      - postgresql-master
    restart: always
    networks:
      - app-tier

  postgresql-master:
    image: docker.io/bitnami/postgresql:14
    container_name: booking_db_container
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=phatdo
      - POSTGRESQL_PASSWORD=Blue_Berry
      - POSTGRESQL_DATABASE=bookingdb
    ports:
      - '5432:5432'
    restart: always
    networks:
      - app-tier

volumes:
  postgresql_master_data:
    driver: local
# To connect postgresql-master you need to get ip address them. Using docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container-ID>
